---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 53015.
--- DateTime: 2025/3/1 16:27
--- 参数列表：
--- 优惠券ID
local voucherId = ARGV[1]
--- 用户ID
local userId = ARGV[2]
--- 订单ID
local orderId = ARGV[3]
--- 数据KEY
local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

--- 判断用库存是否充足
if (tonumber(redis.call('get', stockKey)) <= 0) then
    --- 库存不足
    return 1
end
--- 判断用户是否已经购买过
if (redis.call('sismember', orderKey, userId) == 1) then
    --- 用户已经购买过
    return 2
end
--- 扣减库存，并记录用户购买信息
redis.call('incrby', stockKey, -1)
redis.call('sadd', orderKey, userId)
--- 发送消息
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0